Update README.md
facebookresearch/CompilerGym pull request #183
Opened 2021-04-19 18:29 UTC by JD-ETH

Clang 9 was needed on Ubuntu.

Fixes #{182}

2021-04-19 20:20 UTC, ChrisCummins requested changes
Thanks for this @JD-ETH! It can be slightly simplified as

2021-04-19 20:20 UTC, ChrisCummins commented on README.md
> +sudo apt install clang clang-9 libtinfo5 libjpeg-dev patchelf
```suggestion
sudo apt install clang-9 libtinfo5 libjpeg-dev patchelf
```

2021-04-20 06:06 UTC, JD-ETH commented
@ChrisCummins sure

2021-04-20 07:44 UTC, ChrisCummins approved these changes
LGTM. Thanks!

2021-04-20 10:06 UTC, merged